DELETE http://localhost:3003/api/blogs/65800adaf3a85bb79fea791b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hdHRpbWVpa2FsYWluZW4iLCJpZCI6IjY1ODAwOTA0NjdmZTc2MGI1NjZkMmZkMCIsImlhdCI6MTcwMjkzMDI0MH0.a9txse0Z9BjVazI0p43jOf7m4UgEH2ipSNLrG_c04D8